### ISSUE TITLE
command 'rails.fastNavigation' not found

### ISSUE THREAD

**Issue by morishin** [jemmyw/vscode-rails-fast-nav#1]
I installed this package from Marketplace.
`command 'rails.fastNavigation' not found` is shown when I press 'alt+r'.
My VS Code version is 1.18.0.
Please tell me how to resolve error.

**Comment by jemmyw** [comment]
Hi @morishin 

Do you have a file from a Rails project open in the text editor? The commands are only available when editing a file.

If you have a file open you're still seeing the problem, try opening the Command Palette and typing "Rails", you should see a bunch of commands, one of them being "Rails: Fast navigation"

**Comment by morishin** [comment]
The directory structure of the project I opened in editor was not normal one...
This package worked for another simple rails project 😓 
Thank you!
