### ISSUE TITLE
In a model with namespace alt+r show a blank list

### ISSUE THREAD

**Issue by kikyous** [jemmyw/vscode-rails-fast-nav#6]
![2019-03-24 13-53-08 的屏幕截图](https://user-images.githubusercontent.com/818616/54875542-3e325100-4e3c-11e9-9b4a-4ebf247b8bee.png)

model path is app/model/crm/purchase.rb

**Comment by jemmyw** [comment]
Appears to pick up the spec file, but not controller or other related files

**Comment by jemmyw** [comment]
@kikyous v1.3.0 released with a fix for this issue. Let me know if that is working for you.

**Comment by kikyous** [comment]
@jemmyw thanks for update, I will try it tonight.

**Comment by kikyous** [comment]
![2019-03-26 21-19-56 的屏幕截图](https://user-images.githubusercontent.com/818616/55000192-f31b6800-500c-11e9-9fc8-480910aaa374.png)

I can only goto controller file from model, is this right behavior?

**Comment by jemmyw** [comment]
What other files were you expecting? It should show controllers, helpers, tests, fixtures, from the model. It does not show views.
