### ISSUE TITLE
Add option for detecting view formats other than ERB

### ISSUE THREAD

**Issue by AaronH** [jemmyw/vscode-rails-fast-nav#7]
It would be great to have a way to search set a different view extension so that this extension could work with things like HAML. 

Even better would be the ability to search for multiple extensions at once as large projects of differing ages can use a combination of both ERB and HAML depending on the vintage.

**Comment by jemmyw** [comment]
@AaronH it should already support any file extension for views. Matching is done on viewpath/* I've tested with .html.haml files and it works fine.

**Comment by AaronH** [comment]
Oops! I see the issue now. 

You can navigate to the views from the controller, but when in a model only the controller and test shortcuts appear. It would be handy to also have the views there, but obviously that's a different issue. Gonna close this one.
